<a href="https://colab.research.google.com/github/Ritesh24f1001677/MACHINE_LEARNING/blob/main/OPPE_Revision_Session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
data=load_iris(as_frame=True)
dtf=data.frame
dtf

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [7]:
X=dtf.drop('target',axis=1)
y=dtf['target']

In [8]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=42)

In [11]:
# KNN
# Logistic Regression
# Tree
# Random forest
# MLP
# SVM

In [12]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(X_train,y_train)

LogisticRegression()

In [13]:
y_pred=logreg.predict(X_test)

In [14]:
from sklearn.metrics import f1_score, confusion_matrix, precision_score, recall_score, accuracy_score

In [15]:
accuracy_score(y_test,y_pred)

1.0

In [16]:
precision_score(y_test,y_pred,average=None)

array([1., 1., 1.])

In [17]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [18]:
logreg.predict_proba(X_test)

array([[3.80392750e-03, 8.27739664e-01, 1.68456409e-01],
       [9.46973015e-01, 5.30267859e-02, 1.98766047e-07],
       [8.86161500e-09, 1.54855320e-03, 9.98451438e-01],
       [6.48590621e-03, 7.92228336e-01, 2.01285757e-01],
       [1.45781656e-03, 7.74128267e-01, 2.24413916e-01],
       [9.55901156e-01, 4.40986681e-02, 1.76042219e-07],
       [7.80188690e-02, 9.07698116e-01, 1.42830151e-02],
       [1.63889525e-04, 1.54555442e-01, 8.45280669e-01],
       [2.22404287e-03, 7.62851897e-01, 2.34924060e-01],
       [2.84406661e-02, 9.45734619e-01, 2.58247146e-02],
       [4.45531359e-04, 2.42557411e-01, 7.56997057e-01],
       [9.68124675e-01, 3.18752473e-02, 7.79547112e-08],
       [9.73006419e-01, 2.69935481e-02, 3.31813249e-08],
       [9.61906094e-01, 3.80937957e-02, 1.10701468e-07],
       [9.79286250e-01, 2.07136860e-02, 6.44533866e-08],
       [4.59528720e-03, 7.12372206e-01, 2.83032507e-01],
       [7.31736898e-06, 2.41375663e-02, 9.75855116e-01],
       [2.73625321e-02, 9.47766

In [19]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=5)
kn.fit(X_train,y_train)

KNeighborsClassifier()

In [20]:
y_pred=kn.predict(X_test)

In [21]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [22]:
accuracy_score(y_test,y_pred)

1.0

In [23]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler

StandardScaler()

In [24]:
X_scaled=scaler.fit_transform(X_train)
knn=KNeighborsClassifier(n_neighbors=5)
knn

KNeighborsClassifier()

In [25]:
knn


KNeighborsClassifier()

In [26]:
knn.fit(X_scaled,y_train)

KNeighborsClassifier()

In [27]:
knn

KNeighborsClassifier()

In [28]:
y_pred=knn.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


In [29]:
y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [30]:
accuracy_score(y_test,y_pred)

0.36666666666666664

In [31]:
from sklearn.svm import SVC  # i will remember
svm=SVC()
svm

SVC()

In [32]:
svm.fit(X_train,y_train)

SVC()

In [33]:
svm.score(X_test,y_test)  # accuracy trick

1.0

 # Hyper Parameter tuning



In [34]:
from sklearn.model_selection import GridSearchCV
param_grid={
    'C':[0.1,0.01],
    'kernel':['linear','rbf']
}


In [35]:
grid=GridSearchCV(SVC(),param_grid,cv=2)
grid

GridSearchCV(cv=2, estimator=SVC(),
             param_grid={'C': [0.1, 0.01], 'kernel': ['linear', 'rbf']})

In [36]:
grid.fit(X_train,y_train)

GridSearchCV(cv=2, estimator=SVC(),
             param_grid={'C': [0.1, 0.01], 'kernel': ['linear', 'rbf']})

In [37]:
grid.best_score_

np.float64(0.925)

In [38]:
grid.best_params_

{'C': 0.1, 'kernel': 'linear'}

In [39]:
grid.best_estimator_

SVC(C=0.1, kernel='linear')

# Tree based Model

In [40]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()
tree.fit(X_train, y_train)

DecisionTreeClassifier()

In [41]:
y_pred=tree.predict(X_test)

In [42]:
accuracy_score(y_test,y_pred)

1.0

In [43]:
tree.feature_importances_

array([0.        , 0.01667014, 0.40593501, 0.57739485])

In [46]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [47]:
rf

RandomForestClassifier()

In [49]:
rf.fit(X_train, y_train)

RandomForestClassifier()

In [51]:
y_pred=rf.predict(X_test)

In [52]:
accuracy_score(y_test,y_pred)

1.0

In [54]:
# n_estimators
# max_depth
# criterion - gini and entropy

In [55]:
param_grid={
    'n_estimators':[20,50],
    'max_depth':[2,3,5],
    'criterion':['gini','entropy']
}

In [59]:
grid1=GridSearchCV(RandomForestClassifier(),param_grid,cv=3)

In [60]:
grid1

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 5], 'n_estimators': [20, 50]})

In [62]:
grid1.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 5], 'n_estimators': [20, 50]})

In [65]:
grid1.best_score_

np.float64(0.9583333333333334)

In [67]:
grid1.best_estimator_

RandomForestClassifier(max_depth=3, n_estimators=20)

In [68]:
grid1.best_params_

{'criterion': 'gini', 'max_depth': 3, 'n_estimators': 20}

In [69]:
grid1.get_params()

{'cv': 3,
 'error_score': nan,
 'estimator__bootstrap': True,
 'estimator__ccp_alpha': 0.0,
 'estimator__class_weight': None,
 'estimator__criterion': 'gini',
 'estimator__max_depth': None,
 'estimator__max_features': 'sqrt',
 'estimator__max_leaf_nodes': None,
 'estimator__max_samples': None,
 'estimator__min_impurity_decrease': 0.0,
 'estimator__min_samples_leaf': 1,
 'estimator__min_samples_split': 2,
 'estimator__min_weight_fraction_leaf': 0.0,
 'estimator__monotonic_cst': None,
 'estimator__n_estimators': 100,
 'estimator__n_jobs': None,
 'estimator__oob_score': False,
 'estimator__random_state': None,
 'estimator__verbose': 0,
 'estimator__warm_start': False,
 'estimator': RandomForestClassifier(),
 'n_jobs': None,
 'param_grid': {'n_estimators': [20, 50],
  'max_depth': [2, 3, 5],
  'criterion': ['gini', 'entropy']},
 'pre_dispatch': '2*n_jobs',
 'refit': True,
 'return_train_score': False,
 'scoring': None,
 'verbose': 0}

In [74]:
# GradientBoosting
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
gradb=GradientBoostingClassifier(n_estimators=100)
ada=AdaBoostClassifier(n_estimators=50)
ada.fit(X_train,y_train)

AdaBoostClassifier()

# MLP Session
# Preprocessing revision we have to do.............

In [75]:
from sklearn.model_selection import train_test_split

In [76]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.75,random_state=0)


In [77]:
X_train.shape

(112, 4)

In [79]:
X_test.shape,X_test.shape

((38, 4), (38, 4))

In [81]:
from sklearn.datasets import load_iris
iris=load_iris(as_frame=True)
dtf=iris.frame

In [82]:
dtf

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [83]:
X=dtf.drop('target',axis=1)
y=dtf['target']

In [85]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [86]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
131                7.9               3.8                6.4               2.0
19                 5.1               3.8                1.5               0.3
42                 4.4               3.2                1.3               0.2
96                 5.7               2.9                4.2               1.3
58                 6.6               2.9                4.6               1.3
..                 ...               ...                ...               ...
143                6.8               3.2                5.9               2.3
60                 5.0               2.0                3.5               1.0
148                6.2               3.4                5.4               2.3
95                 5.7               3.0                4.2               1.2
22                 4.6               3.6                1.0               0.2

[120 rows x 4 columns]

In [87]:
X_train.shape

(120, 4)

In [88]:
from sklearn.feature_selection  import SelectKBest

In [92]:
Kbest=SelectKBest(k=1)
X_train_new=Kbest.fit_transform(X_train,y_train)

In [93]:
X_train_new

array([[6.4],
       [1.5],
       [1.3],
       [4.2],
       [4.6],
       [1.4],
       [1.4],
       [4. ],
       [1.3],
       [4.9],
       [1.5],
       [4.8],
       [5.5],
       [5.6],
       [1.4],
       [6.7],
       [1.5],
       [5.5],
       [5.6],
       [1.3],
       [1.3],
       [4.7],
       [4.5],
       [4.7],
       [1.6],
       [3.8],
       [4.5],
       [4.6],
       [4.3],
       [5. ],
       [5.1],
       [5. ],
       [5. ],
       [1.2],
       [6.1],
       [5.5],
       [6.6],
       [5.6],
       [4.9],
       [3.3],
       [1.7],
       [5.7],
       [5.1],
       [1.5],
       [3.9],
       [1.5],
       [6.1],
       [5.1],
       [5. ],
       [1.5],
       [1.1],
       [4.5],
       [1.6],
       [5.9],
       [4. ],
       [4.5],
       [1.4],
       [1.7],
       [5.7],
       [1.5],
       [6.1],
       [6.7],
       [4. ],
       [1.7],
       [3.3],
       [1.5],
       [5.1],
       [1.6],
       [1.6],
       [4.7],
       [1.5],
      

In [98]:
Kbest.get_feature_names_out()

array(['petal length (cm)'], dtype=object)

In [101]:
# RFE
from sklearn.feature_selection import RFE
from sklearn.linear_model import Perceptron
model=Perceptron(eta0=1)
model

Perceptron(eta0=1)

In [102]:
rfe=RFE(estimator=model,n_features_to_select=2)

In [103]:
rfe

RFE(estimator=Perceptron(eta0=1), n_features_to_select=2)

In [104]:
X_train_rfe=rfe.fit_transform(X_train,y_train)

In [106]:
X_train_rfe

array([[3.8, 2. ],
       [3.8, 0.3],
       [3.2, 0.2],
       [2.9, 1.3],
       [2.9, 1.3],
       [3.4, 0.2],
       [3.5, 0.2],
       [2.6, 1.2],
       [2.3, 0.3],
       [2.5, 1.5],
       [3.1, 0.1],
       [3.2, 1.8],
       [3.1, 1.8],
       [2.8, 2.2],
       [3.5, 0.3],
       [3.8, 2.2],
       [3.4, 0.4],
       [3. , 2.1],
       [2.8, 2.1],
       [3.5, 0.2],
       [3.5, 0.3],
       [2.9, 1.4],
       [2.5, 1.7],
       [3.3, 1.6],
       [3.2, 0.2],
       [2.4, 1.1],
       [3.4, 1.6],
       [2.8, 1.5],
       [2.9, 1.3],
       [2.5, 1.9],
       [3.1, 2.3],
       [2.5, 2. ],
       [3. , 1.7],
       [4. , 0.2],
       [3.6, 2.5],
       [3. , 1.8],
       [3. , 2.1],
       [2.9, 1.8],
       [2.7, 1.8],
       [2.3, 1. ],
       [3.9, 0.4],
       [3.2, 2.3],
       [2.7, 1.6],
       [4.4, 0.4],
       [2.5, 1.1],
       [3.7, 0.2],
       [2.8, 1.9],
       [2.7, 1.9],
       [2.2, 1.5],
       [4.1, 0.1],
       [3. , 0.1],
       [2.8, 1.3],
       [3. ,

In [108]:
rfe.get_feature_names_out()

array(['sepal width (cm)', 'petal width (cm)'], dtype=object)

In [109]:
rfe.n_features_in_

4

In [116]:
rfe1=RFE(estimator=LogisticRegression(),n_features_to_select=2)

In [117]:
rfe1

RFE(estimator=LogisticRegression(), n_features_to_select=2)

In [119]:
rfe1.fit(X_train,y_train)

RFE(estimator=LogisticRegression(), n_features_to_select=2)

In [120]:
rfe1.get_feature_names_out()

array(['petal length (cm)', 'petal width (cm)'], dtype=object)