<a href="https://colab.research.google.com/github/Ritesh24f1001677/MACHINE_LEARNING/blob/main/Viva_Level2_Preparation_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# Har Har Mahadev
---


---
# Data Loading for practice and test may be
---

In [7]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
data=load_iris()
X=data.data
y=data.target

In [57]:
from sklearn.datasets import load_diabetes
diabetes=load_diabetes(as_frame=True)
df1=diabetes.frame
df1.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019907 -0.017646   151.0  
1 -0.039493 -0.068332 -0.092204    75.0  
2 -0.002592  0.002861 -0.025930   141.0  
3  0.034309  0.022688 -0.009362   206.0  
4 -0.002592 -0.031988 -0.046641   135.0

In [56]:
from sklearn.datasets import load_digits
digit=load_digits(as_frame=True)
df2=digit.frame
df2.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [52]:
from sklearn.datasets import load_linnerud
linnerud=load_linnerud(as_frame=True)
df3=linnerud.frame
df3.head()

Chins  Situps  Jumps  Weight  Waist  Pulse
0    5.0   162.0   60.0   191.0   36.0   50.0
1    2.0   110.0   60.0   189.0   37.0   52.0
2   12.0   101.0  101.0   193.0   38.0   58.0
3   12.0   105.0   37.0   162.0   35.0   62.0
4   13.0   155.0   58.0   189.0   35.0   46.0

In [53]:
from sklearn.datasets import load_wine
wine=load_wine(as_frame=True)
df4=wine.frame
df4.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [54]:
from sklearn.datasets import load_breast_cancer
cancer=load_breast_cancer(as_frame=True)
df5=cancer.frame
df5.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [55]:
from sklearn.datasets import fetch_california_housing
housing =fetch_california_housing(as_frame=True)
df6=housing.frame
df6.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422

In [59]:
y=df['target']
X=df.drop('target', axis=1)

In [60]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [61]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_val,y_train, y_val=train_test_split(X,y,test_size=0.2,random_state=42)

In [65]:
X_train.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                4.6               3.6                1.0               0.2
15                5.7               4.4                1.5               0.4
65                6.7               3.1                4.4               1.4
11                4.8               3.4                1.6               0.2
42                4.4               3.2                1.3               0.2

In [66]:
y_train.head()

22    0
15    0
65    1
11    0
42    0
Name: target, dtype: int64

In [69]:
X_val.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4

In [74]:
dt={
    'Category':['A','B','A','C','B'],
    'Value':[10,20,15,30,25]
    }

In [75]:
dtf=pd.DataFrame(dt)

In [80]:
dtf

Category  Value
0        A     10
1        B     20
2        A     15
3        C     30
4        B     25

In [84]:
encoded_dtf=pd.get_dummies(dtf,columns=['Category'],dtype='float')
encoded_dtf

Value  Category_A  Category_B  Category_C
0     10         1.0         0.0         0.0
1     20         0.0         1.0         0.0
2     15         1.0         0.0         0.0
3     30         0.0         0.0         1.0
4     25         0.0         1.0         0.0

In [343]:
encoded_dtf

Value  Category_A  Category_B  Category_C
0     10         1.0         0.0         0.0
1     20         0.0         1.0         0.0
2     15         1.0         0.0         0.0
3     30         0.0         0.0         1.0
4     25         0.0         1.0         0.0

---
# Data preprocessing contains, PCA, Imputing, scaling, vecorizer, ordinal , label Encoder..... and so on.......

# PCA principle component features

In [87]:
# principle features,  like suppose we have 4 features, so we can get 2 features,
# get best features
# it is also called dimensionality reduction
# X1, X2, X3, X4, so we cannot able to visualize all the 4 feauteres.
# X1, X2, X3-----------> X1,X4
# it can take a combination of the data and do the dimensionality redution.....


In [99]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)

In [100]:
?pca

In [101]:
from sklearn.datasets import load_iris
iris=load_iris(as_frame=True)
dtf7=iris.frame
dtf7.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [102]:
iris_df=dtf7.drop('target',axis=1)

In [103]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [104]:
iris_pca=pca.fit_transform(iris_df)

In [105]:
iris_pca

array([[-2.68412563,  0.31939725],
       [-2.71414169, -0.17700123],
       [-2.88899057, -0.14494943],
       [-2.74534286, -0.31829898],
       [-2.72871654,  0.32675451],
       [-2.28085963,  0.74133045],
       [-2.82053775, -0.08946138],
       [-2.62614497,  0.16338496],
       [-2.88638273, -0.57831175],
       [-2.6727558 , -0.11377425],
       [-2.50694709,  0.6450689 ],
       [-2.61275523,  0.01472994],
       [-2.78610927, -0.235112  ],
       [-3.22380374, -0.51139459],
       [-2.64475039,  1.17876464],
       [-2.38603903,  1.33806233],
       [-2.62352788,  0.81067951],
       [-2.64829671,  0.31184914],
       [-2.19982032,  0.87283904],
       [-2.5879864 ,  0.51356031],
       [-2.31025622,  0.39134594],
       [-2.54370523,  0.43299606],
       [-3.21593942,  0.13346807],
       [-2.30273318,  0.09870885],
       [-2.35575405, -0.03728186],
       [-2.50666891, -0.14601688],
       [-2.46882007,  0.13095149],
       [-2.56231991,  0.36771886],
       [-2.63953472,

In [106]:
pca.explained_variance_ratio_


array([0.92461872, 0.05306648])

In [107]:
pca.explained_variance_

array([4.22824171, 0.24267075])

In [111]:
pca.get_feature_names_out()

array(['pca0', 'pca1'], dtype=object)

In [112]:
?pca

In [113]:
pca.singular_values_

array([25.09996044,  6.01314738])

In [114]:
pca.noise_variance_

np.float64(0.05102229650817785)

In [121]:
pca.components_

array([[ 0.36138659, -0.08452251,  0.85667061,  0.3582892 ],
       [ 0.65658877,  0.73016143, -0.17337266, -0.07548102]])

In [123]:
pd.DataFrame(pca.components_, columns=iris_df.columns)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.361387         -0.084523           0.856671          0.358289
1           0.656589          0.730161          -0.173373         -0.075481

In [124]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer

In [125]:
pipe=Pipeline([
    ('si',SimpleImputer()),
    ('ms',MinMaxScaler())
])

In [126]:
pipe

Pipeline(steps=[('si', SimpleImputer()), ('ms', MinMaxScaler())])

In [128]:
iris_t=pipe.fit_transform(iris_pca)

In [129]:
iris_t

array([[0.07688326, 0.60048735],
       [0.07260713, 0.41246733],
       [0.04769793, 0.42460754],
       [0.06816217, 0.35894822],
       [0.07053078, 0.60327405],
       [0.13433306, 0.76030228],
       [0.05744981, 0.44562465],
       [0.08514326, 0.54139484],
       [0.04806944, 0.26046361],
       [0.07850302, 0.43641571],
       [0.10212435, 0.72384146],
       [0.08705078, 0.48508902],
       [0.06235453, 0.39045681],
       [0.        , 0.28580972],
       [0.08249271, 0.9259885 ],
       [0.11934907, 0.98632542],
       [0.08551609, 0.78656951],
       [0.08198749, 0.59762837],
       [0.14587803, 0.81011357],
       [0.09057938, 0.67403017],
       [0.13014519, 0.62773923],
       [0.09688773, 0.64351498],
       [0.00112036, 0.53006327],
       [0.13121693, 0.51689758],
       [0.12366351, 0.4653886 ],
       [0.10216398, 0.42420322],
       [0.10755597, 0.52911007],
       [0.09423586, 0.61879005],
       [0.08323574, 0.59770065],
       [0.08431065, 0.40490712],
       [0.

In [130]:
pipe['si']

SimpleImputer()

In [131]:
pipe['ms']

MinMaxScaler()

In [132]:
pipe.get_params()

{'memory': None,
 'steps': [('si', SimpleImputer()), ('ms', MinMaxScaler())],
 'transform_input': None,
 'verbose': False,
 'si': SimpleImputer(),
 'ms': MinMaxScaler(),
 'si__add_indicator': False,
 'si__copy': True,
 'si__fill_value': None,
 'si__keep_empty_features': False,
 'si__missing_values': nan,
 'si__strategy': 'mean',
 'ms__clip': False,
 'ms__copy': True,
 'ms__feature_range': (0, 1)}

In [134]:
dtf

Category  Value
0        A     10
1        B     20
2        A     15
3        C     30
4        B     25

In [135]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder

In [142]:
ct=ColumnTransformer([
    ('si',SimpleImputer(strategy='most_frequent'),['Category','Value']),
    ('le',LabelEncoder(),['Category']),
    ('ms',MinMaxScaler(),["Value"])
])

In [143]:
ct

ColumnTransformer(transformers=[('si', SimpleImputer(strategy='most_frequent'),
                                 ['Category', 'Value']),
                                ('le', LabelEncoder(), ['Category']),
                                ('ms', MinMaxScaler(), ['Value'])])

In [148]:
data_x={
    'Age':[25,30,None,45,40],
    'Fare':[100,None, 80,75,60]
}
data_x

{'Age': [25, 30, None, 45, 40], 'Fare': [100, None, 80, 75, 60]}

In [151]:
v2=pd.DataFrame(data_x)
v2

Age   Fare
0  25.0  100.0
1  30.0    NaN
2   NaN   80.0
3  45.0   75.0
4  40.0   60.0

# 1.KNN Imputer and Simple Imputer concept

In [157]:
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
si=SimpleImputer(strategy='mean',missing_values=np.nan)
si.fit_transform((v2))

array([[ 25.  , 100.  ],
       [ 30.  ,  78.75],
       [ 35.  ,  80.  ],
       [ 45.  ,  75.  ],
       [ 40.  ,  60.  ]])

In [159]:
knn=KNNImputer(n_neighbors=2,missing_values=np.nan)
knn

KNNImputer(n_neighbors=2)

In [162]:
knn.fit_transform(v2)

array([[ 25. , 100. ],
       [ 30. ,  80. ],
       [ 42.5,  80. ],
       [ 45. ,  75. ],
       [ 40. ,  60. ]])

# 2.Dict_vectorizer

In [164]:
dict=[
    {'city':'New_York','temperature':21},
    {'city':'San_Francisco','temperature':18},
    {'city':'Chicago','temperature':15}
]

In [174]:
from sklearn.feature_extraction import DictVectorizer, FeatureHasher
dv=DictVectorizer(sparse=False)
dv

DictVectorizer(sparse=False)

In [175]:
print(dv.fit_transform(dict))

[[ 0.  1.  0. 21.]
 [ 0.  0.  1. 18.]
 [ 1.  0.  0. 15.]]


In [189]:
fh=FeatureHasher(n_features=3,input_type='dict')

In [190]:
fh

FeatureHasher(n_features=3)

In [192]:
x=fh.fit_transform(dict)

In [342]:
x.toarray()

array([[  0., -21.,  -1.],
       [ -1., -18.,   0.],
       [  1., -15.,   0.]])

---
# Preprocessing Includes encoding, scaling, pipeline, column transformer, feature union.
---

In [197]:
from sklearn import datasets

In [202]:
dd=datasets.fetch_openml(name='titanic',version=1)

In [206]:
dd.DESCR

'**Author**: Frank E. Harrell Jr., Thomas Cason  \n**Source**: [Vanderbilt Biostatistics](http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic.html)  \n**Please cite**:   \n\nThe original Titanic dataset, describing the survival status of individual passengers on the Titanic. The titanic data does not contain information from the crew, but it does contain actual ages of half of the passengers. The principal source for data about Titanic passengers is the Encyclopedia Titanica. The datasets used here were begun by a variety of researchers. One of the original sources is Eaton & Haas (1994) Titanic: Triumph and Tragedy, Patrick Stephens Ltd, which includes a passenger list created by many researchers and edited by Michael A. Findlay.\n\nThomas Cason of UVa has greatly updated and improved the titanic data frame using the Encyclopedia Titanica and created the dataset here. Some duplicate passengers have been dropped, many errors corrected, many missing ages filled in, and new v

In [214]:
ddf=dd.data

In [216]:
ddf

pclass                                             name     sex  \
0          1                    Allen, Miss. Elisabeth Walton  female   
1          1                   Allison, Master. Hudson Trevor    male   
2          1                     Allison, Miss. Helen Loraine  female   
3          1             Allison, Mr. Hudson Joshua Creighton    male   
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
...      ...                                              ...     ...   
1304       3                             Zabour, Miss. Hileni  female   
1305       3                            Zabour, Miss. Thamine  female   
1306       3                        Zakarian, Mr. Mapriededer    male   
1307       3                              Zakarian, Mr. Ortin    male   
1308       3                               Zimmerman, Mr. Leo    male   

          age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0     29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1      0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2      2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3     30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4     25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
...       ...    ...    ...     ...       ...      ...      ...  ...    ...   
1304  14.5000      1      0    2665   14.4542      NaN        C  NaN  328.0   
1305      NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   
1306  26.5000      0      0    2656    7.2250      NaN        C  NaN  304.0   
1307  27.0000      0      0    2670    7.2250      NaN        C  NaN    NaN   
1308  29.0000      0      0  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 13 columns]

In [217]:
ddf['age'].isna().sum()

np.int64(263)

In [219]:
si=SimpleImputer(strategy='mean',missing_values=np.nan)
si.fit_transform(ddf[['age']]).shape

(1309, 1)

In [220]:
knn=KNNImputer(n_neighbors=5)
knn.fit_transform(ddf[['age','fare']])

array([[ 29.    , 211.3375],
       [  0.9167, 151.55  ],
       [  2.    , 151.55  ],
       ...,
       [ 26.5   ,   7.225 ],
       [ 27.    ,   7.225 ],
       [ 29.    ,   7.875 ]])

In [227]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
ohe.fit_transform(ddf[['sex','embarked']])

array([[1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0.],
       ...,
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0.]])

In [232]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(ddf['sex'])

array([0, 1, 0, ..., 1, 1, 1])

In [234]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
oe.fit_transform(ddf[['embarked']])

array([[2.],
       [2.],
       [2.],
       ...,
       [0.],
       [0.],
       [2.]])

In [239]:
from sklearn.feature_selection import SelectKBest
sk=SelectKBest(k=2)
sk

SelectKBest(k=2)

In [242]:
pr=pd.read_csv('/content/data (2).csv')

In [243]:
pr

customer_id                name  age  gender  \
0     4d623250-b704-4df8-aea2-5403458a1d6e         Sean Nelson   41       F   
1     e5593c2b-1ed8-4fe8-be82-acced82f9711          Eddie Wood   38  Female   
2     7240c499-1c3d-4188-8b12-76c515aff931      Abigail Graham   11       M   
3     43c7001d-4c6d-4011-aa02-e9b57c0e3944   Jessica Contreras   40     NaN   
4     4fb0f886-7e67-4982-bfe0-959272cece1b         Kelly Olson   20  Female   
...                                    ...                 ...  ...     ...   
9995  f7a93a70-6713-4200-84a0-8e6845ecbd57          Cody Brown   40       F   
9996  daf9abc9-1ff9-4edb-8a20-da6ae77ea13e         Dana Fields   48  Female   
9997  6c7ddfb3-459d-41f9-bd1c-9a2acb0c7eee  Christine Humphrey   35  Female   
9998  1729037e-0a06-47a6-91c6-52a0ece6506b    Pamela Rodriguez   59     NaN   
9999  3dadf4ed-30f1-456b-a13d-9f8351851807        Darryl Owens   40  female   

                       email     join_date last_purchase  total_spent  \
0     tylersmith@example.org  Dec 19, 2020    2025-04-02   238.517142   
1          xreed@example.net    30/10/2021    2024-12-25    93.126377   
2     cartersara@example.com  May 03, 2022    2025-05-10   873.017713   
3       fsalazar@example.org  Aug 03, 2021           NaN   401.703726   
4       robert21@example.org  Apr 05, 2024    2025-05-07  1198.186419   
...                      ...           ...           ...          ...   
9995   vsullivan@example.net    2020-07-14    2024-09-01   615.638525   
9996       amy07@example.com    2022-10-24    2025-01-27  1134.668932   
9997   sharpsean@example.net    07/01/2024    2024-12-07  1339.414613   
9998     fgordon@example.com  Sep 01, 2024    2025-03-13   676.673223   
9999     wthomas@example.com    2023-12-11    2024-08-23  1002.374697   

      purchase_count  country                    city postal_code  \
0               51.0  Germany       Port Michaelmouth       06803   
1               31.0      USA                 Brig...       64245   
2               87.0  Germany           Port Kevinton       43574   
3                NaN    India           Gillespietown         NaN   
4               34.0  Germany               jamesberg       82358   
...              ...      ...                     ...         ...   
9995            98.0       UK            ANTHONYMOUTH       15589   
9996            97.0      NaN               WEST JODY       86614   
9997             6.0      USA  SOUTH ELIZABETHBOROUGH       33931   
9998            89.0    Japan          East Erikville       70357   
9999            64.0   France          East Johnmouth      AB-123   

     subscription_type  credit_score is_active  payment_method  \
0            Corporate           663      True             NaN   
1                  NaN           656         N          PayPal   
2                Trial           672         N  Cryptocurrency   
3                Trial           614      True          PayPal   
4              Premium           692         N   Bank Transfer   
...                ...           ...       ...             ...   
9995         Corporate           728      True  Cryptocurrency   
9996             Trial           738      True            Cash   
9997             Trial           850        No             NaN   
9998           Premium           659         N   Bank Transfer   
9999           Premium           734     False          PayPal   

     preferred_category  avg_session_duration device_type campaign_response  
0             Groceries           1066.626690      TABLET               NaN  
1              Clothing            327.762945      mobile                no  
2              Clothing             95.654242      Mobile                No  
3                  Home            498.371991      mobile               NaN  
4             Groceries                   NaN      mobile               YES  
...                 ...                   ...         ...               ...  
9995          Groceries            16

In [246]:
from sklearn.compose import ColumnTransformer

In [263]:
pr.columns

Index(['age', 'gender', 'join_date', 'last_purchase', 'total_spent',
       'purchase_count', 'country', 'subscription_type', 'credit_score',
       'is_active', 'payment_method', 'preferred_category',
       'avg_session_duration', 'device_type', 'campaign_response'],
      dtype='object')

In [264]:
impute_tf=[
    ('mode_imputer',SimpleImputer(strategy='most_frequent'),['postal_code','preferred_category','subscription_type','payment_method','country','gender']),
    ('median_imputer',SimpleImputer(strategy='median'),['avg_session_duration','age']),
    ('cp_imputer',SimpleImputer(strategy='constant',fill_value='missing_resonse'),['campaign_response']),
    ('pc_imputer',SimpleImputer(strategy='constant',fill_value=0),['purchase_count'])
]
impute_ct=ColumnTransformer(transformers=impute_tf,remainder='passthrough').set_output(transform='pandas')
impute_ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('mode_imputer',
                                 SimpleImputer(strategy='most_frequent'),
                                 ['postal_code', 'preferred_category',
                                  'subscription_type', 'payment_method',
                                  'country', 'gender']),
                                ('median_imputer',
                                 SimpleImputer(strategy='median'),
                                 ['avg_session_duration', 'age']),
                                ('cp_imputer',
                                 SimpleImputer(fill_value='missing_resonse',
                                               strategy='constant'),
                                 ['campaign_response']),
                                ('pc_imputer',
                                 SimpleImputer(fill_value=0,
                                               strategy='constant'),
                                 ['purchase_count'])])

In [267]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler, MinMaxScaler, RobustScaler


In [269]:
pr=pr.drop(['customer_id','email','name','city','postal_code'],axis=1, errors='ignore')

In [280]:
encode_tf=[
    ('ohe',OneHotEncoder(sparse_output=False),['country','subscription_type','payment_method','preferred_category','device_type']),
    ('oe',OrdinalEncoder(),['gender','is_active','campaign_response'])
]
encode_ct=ColumnTransformer(transformers=encode_tf,remainder='drop',verbose_feature_names_out=False).set_output(transform='pandas')
pipe1=Pipeline(steps=[('encoding',encode_ct),
                      ('scaling',StandardScaler())]).set_output(transform='pandas')

In [281]:
pipe1

Pipeline(steps=[('encoding',
                 ColumnTransformer(transformers=[('ohe',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['country',
                                                   'subscription_type',
                                                   'payment_method',
                                                   'preferred_category',
                                                   'device_type']),
                                                 ('oe', OrdinalEncoder(),
                                                  ['gender', 'is_active',
                                                   'campaign_response'])],
                                   verbose_feature_names_out=False)),
                ('scaling', StandardScaler())])

In [275]:
from sklearn.preprocessing import StandardScaler
scale_tf=[('ss',StandardScaler(),['age','total_spent','avg_session_duration']),
          ('minmax',MinMaxScaler(),['purchase_count']),
          ('robust',RobustScaler(),['credit_score'])
          ]
scale_ct=ColumnTransformer(transformers=scale_tf,remainder='drop',verbose_feature_names_out=False).set_output(transform='pandas')

In [276]:
scale_ct

ColumnTransformer(transformers=[('ss', StandardScaler(),
                                 ['age', 'total_spent',
                                  'avg_session_duration']),
                                ('minmax', MinMaxScaler(), ['purchase_count']),
                                ('robust', RobustScaler(), ['credit_score'])],
                  verbose_feature_names_out=False)

In [277]:
pipe2=Pipeline(steps=[('scaling',scale_ct)]).set_output(transform='pandas')

In [278]:
pipe2

Pipeline(steps=[('scaling',
                 ColumnTransformer(transformers=[('ss', StandardScaler(),
                                                  ['age', 'total_spent',
                                                   'avg_session_duration']),
                                                 ('minmax', MinMaxScaler(),
                                                  ['purchase_count']),
                                                 ('robust', RobustScaler(),
                                                  ['credit_score'])],
                                   verbose_feature_names_out=False))])

In [282]:
pipe1.fit_transform(pr)

country_Australia  country_Brazil  country_Canada  country_China  \
0             -0.309274       -0.298475       -0.300655      -0.306939   
1             -0.309274       -0.298475       -0.300655      -0.306939   
2             -0.309274       -0.298475       -0.300655      -0.306939   
3             -0.309274       -0.298475       -0.300655      -0.306939   
4             -0.309274       -0.298475       -0.300655      -0.306939   
...                 ...             ...             ...            ...   
9995          -0.309274       -0.298475       -0.300655      -0.306939   
9996          -0.309274       -0.298475       -0.300655      -0.306939   
9997          -0.309274       -0.298475       -0.300655      -0.306939   
9998          -0.309274       -0.298475       -0.300655      -0.306939   
9999          -0.309274       -0.298475       -0.300655      -0.306939   

      country_France  country_Germany  country_India  country_Japan  \
0          -0.309080         3.264202      -0.306354      -0.297082   
1          -0.309080        -0.306354      -0.306354      -0.297082   
2          -0.309080         3.264202      -0.306354      -0.297082   
3          -0.309080        -0.306354       3.264202      -0.297082   
4          -0.309080         3.264202      -0.306354      -0.297082   
...              ...              ...            ...            ...   
9995       -0.309080        -0.306354      -0.306354      -0.297082   
9996       -0.309080        -0.306354      -0.306354      -0.297082   
9997       -0.309080        -0.306354      -0.306354      -0.297082   
9998       -0.309080        -0.306354      -0.306354       3.366074   
9999        3.235412        -0.306354      -0.306354      -0.297082   

      country_UK  country_USA  ...  preferred_category_Home  \
0      -0.301643    -0.298674  ...                -0.427472   
1      -0.301643     3.348136  ...                -0.427472   
2      -0.301643    -0.298674  ...                -0.427472   
3      -0.301643    -0.298674  ...                 2.339336   
4      -0.301643    -0.298674  ...                -0.427472   
...          ...          ...  ...                      ...   
9995    3.315178    -0.298674  ...                -0.427472   
9996   -0.301643    -0.298674  ...                -0.427472   
9997   -0.301643     3.348136  ...                -0.427472   
9998   -0.301643    -0.298674  ...                -0.427472   
9999   -0.301643    -0.298674  ...                -0.427472   

      preferred_category_nan  device_type_Desktop  device_type_Mobile  \
0                  -0.519462            -0.500469           -0.494682   
1                  -0.519462            -0.500469           -0.494682   
2                  -0.519462            -0.500469            2.021502   
3                  -0.519462            -0.500469           -0.494682   
4                  -0.519462            -0.500469           -0.494682   
...                      ...                  ...                 ...   
9995               -0.519462            -0.500469           -0.494682   
9996               -0.519462            -0.500469           -0.494682   
9997               -0.519462            -0.500469           -0.494682   
9998               -0.519462            -0.500469           -0.494682   
9999               -0.519462            -0.500469           -0.494682   

      device_type_TABLET  device_type_desktop  device_type_mobile    gender  \
0               2.011953            -0.509358           -0.498437 -1.490353   
1              -0.497029            -0.509358            2.006272 -0.902020   
2              -0.497029            -0.509358           -0.498437 -0.313687   
3              -0.497029            -0.509358            2.006272       NaN   
4              -0.497029            -0.509358            2.006272 -0.902020   
...                  ...                  ...                 ...       ...   
9995           -0.497029             1.963255           -0.498437 -1.490353  

In [285]:
pipe2.fit_transform(pr)

age  total_spent  avg_session_duration  purchase_count  \
0    -0.250251    -0.920811              1.561425        0.505051   
1    -0.452240    -1.427160             -0.923717        0.303030   
2    -2.270141     1.288950             -1.704407        0.868687   
3    -0.317581    -0.352484             -0.349880             NaN   
4    -1.664174     2.421407                   NaN        0.333333   
...        ...          ...                   ...             ...   
9995 -0.317581     0.392581             -1.475811        0.979798   
9996  0.221057     2.200197             -0.288668        0.969697   
9997 -0.654229     2.913260                   NaN        0.050505   
9998  0.961683     0.605145                   NaN        0.888889   
9999 -0.317581     1.739458              0.938619        0.636364   

      credit_score  
0        -0.253731  
1        -0.305970  
2        -0.186567  
3        -0.619403  
4        -0.037313  
...            ...  
9995      0.231343  
9996      0.305970  
9997      1.141791  
9998     -0.283582  
9999      0.276119  

[10000 rows x 5 columns]

In [288]:
from sklearn.pipeline import FeatureUnion

In [289]:
fe=FeatureUnion(transformer_list=[('encode_tf',pipe1),
                                  ('scale_tf',pipe2)]).set_output(transform='pandas')

In [290]:
fe

FeatureUnion(transformer_list=[('encode_tf',
                                Pipeline(steps=[('encoding',
                                                 ColumnTransformer(transformers=[('ohe',
                                                                                  OneHotEncoder(sparse_output=False),
                                                                                  ['country',
                                                                                   'subscription_type',
                                                                                   'payment_method',
                                                                                   'preferred_category',
                                                                                   'device_type']),
                                                                                 ('oe',
                                                                                  OrdinalEncoder(),
                                                                                  ['gender',
                                                                                   'is_active',
                                                                                   'campaign_response'])],
                                                                   verbose_feature_names_out=False)),
                                                ('scaling',
                                                 StandardScaler())])),
                               ('scale_tf',
                                Pipeline(steps=[('scaling',
                                                 ColumnTransformer(transformers=[('ss',
                                                                                  StandardScaler(),
                                                                                  ['age',
                                                                                   'total_spent',
                                                                                   'avg_session_duration']),
                                                                                 ('minmax',
                                                                                  MinMaxScaler(),
                                                                                  ['purchase_count']),
                                                                                 ('robust',
                                                                                  RobustScaler(),
                                                                                  ['credit_score'])],
                                                                   verbose_feature_names_out=False))]))])

In [341]:
fe.fit_transform(pr)

encode_tf__country_Australia  encode_tf__country_Brazil  \
0                        -0.309274                  -0.298475   
1                        -0.309274                  -0.298475   
2                        -0.309274                  -0.298475   
3                        -0.309274                  -0.298475   
4                        -0.309274                  -0.298475   
...                            ...                        ...   
9995                     -0.309274                  -0.298475   
9996                     -0.309274                  -0.298475   
9997                     -0.309274                  -0.298475   
9998                     -0.309274                  -0.298475   
9999                     -0.309274                  -0.298475   

      encode_tf__country_Canada  encode_tf__country_China  \
0                     -0.300655                 -0.306939   
1                     -0.300655                 -0.306939   
2                     -0.300655                 -0.306939   
3                     -0.300655                 -0.306939   
4                     -0.300655                 -0.306939   
...                         ...                       ...   
9995                  -0.300655                 -0.306939   
9996                  -0.300655                 -0.306939   
9997                  -0.300655                 -0.306939   
9998                  -0.300655                 -0.306939   
9999                  -0.300655                 -0.306939   

      encode_tf__country_France  encode_tf__country_Germany  \
0                     -0.309080                    3.264202   
1                     -0.309080                   -0.306354   
2                     -0.309080                    3.264202   
3                     -0.309080                   -0.306354   
4                     -0.309080                    3.264202   
...                         ...                         ...   
9995                  -0.309080                   -0.306354   
9996                  -0.309080                   -0.306354   
9997                  -0.309080                   -0.306354   
9998                  -0.309080                   -0.306354   
9999                   3.235412                   -0.306354   

      encode_tf__country_India  encode_tf__country_Japan  \
0                    -0.306354                 -0.297082   
1                    -0.306354                 -0.297082   
2                    -0.306354                 -0.297082   
3                     3.264202                 -0.297082   
4                    -0.306354                 -0.297082   
...                        ...                       ...   
9995                 -0.306354                 -0.297082   
9996                 -0.306354                 -0.297082   
9997                 -0.306354                 -0.297082   
9998                 -0.306354                  3.366074   
9999                 -0.306354                 -0.297082   

      encode_tf__country_UK  encode_tf__country_USA  ...  \
0                 -0.301643               -0.298674  ...   
1                 -0.301643                3.348136  ...   
2                 -0.301643               -0.298674  ...   
3                 -0.301643               -0.298674  ...   
4                 -0.301643               -0.298674  ...   
...                     ...                     ...  ...   
9995               3.315178               -0.298674  ...   
9996              -0.301643               -0.298674  ...   
9997              -0.301643                3.348136  ...   
9998              -0.301643               -0.298674  ...   
9999              -0.301643               -0.298674  ...   

      encode_tf__device_type_desktop  encode_tf__device_type_mobile  \
0                          -0.509358                      -0.498437   
1                          -0.509358                       2.006272   
2                          -0.509358                      -0.498437   
3        

---
# Model_training Revision Linear Regression, tree based model , and voting , regressor
---

In [298]:
from sklearn.datasets import load_diabetes
dia=load_diabetes(as_frame=True)
diaf=dia.frame
diaf

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019907 -0.017646   151.0  
1   -0.039493 -0.068332 -0.092204    75.0  
2   -0.002592  0.002861 -0.025930   141.0  
3    0.034309  0.022688 -0.009362   206.0  
4   -0.002592 -0.031988 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018114  0.044485   104.0  
439 -0.011080 -0.046883  0.015491   132.0  
440  0.026560  0.044529 -0.025930   220.0  
441 -0.039493 -0.004222  0.003064    57.0  

[442 rows x 11 columns]

In [302]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge, Perceptron
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [307]:
dt=DecisionTreeRegressor()
dt

DecisionTreeRegressor()

In [308]:
dt.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [309]:
lr=LinearRegression()

In [310]:
lr

LinearRegression()

In [311]:
lr.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

In [316]:
from sklearn.model_selection import train_test_split
X=diaf.drop('target',axis=1)
y=diaf['target']
X_train, X_val, y_train, y_val=train_test_split(X,y,test_size=0.2,random_state=42)
lr.fit(X,y)

LinearRegression()

In [317]:
lr.predict(X_val)

array([146.64558568, 174.72103207, 142.31126791, 284.13932209,
       124.51672384,  99.13924946, 257.23492156, 192.32218372,
        97.80405886, 114.24456339, 100.70810916, 166.82164929,
        57.49340026, 207.99702587, 103.56515315, 129.84290324,
       221.77450036, 244.30103923, 191.16896496, 214.02877593,
       213.58462442,  89.83353846,  72.73116856, 189.19505093,
       158.71516713, 155.51063293, 183.497196  , 172.85421282,
        52.60911672, 113.03485904, 172.14766276,  91.00591229,
       136.93257456, 182.64651752, 172.55288732, 199.28001608,
       127.75230658, 124.02163345, 148.49374458,  58.62131994,
        73.91017087, 105.2051755 , 159.93677518, 148.37964317,
       177.27157771,  63.27231315,  77.05671154, 112.82234716,
        52.54148927, 170.67256752, 150.50028158,  69.84285129,
        95.10108423, 109.99895704, 177.17487964, 152.75958287,
        98.7573858 , 206.11667725, 124.01754066,  80.48131518,
       191.53493643, 207.82676612, 140.41937377, 106.92

In [318]:
lr.coef_

array([ -10.0098663 , -239.81564367,  519.84592005,  324.3846455 ,
       -792.17563855,  476.73902101,  101.04326794,  177.06323767,
        751.27369956,   67.62669218])

In [319]:
lr.intercept_

np.float64(152.13348416289597)

In [321]:
lr.score(X_val,y_val)

0.477690321501004

In [323]:
from sklearn.preprocessing import PolynomialFeatures
pf=PolynomialFeatures(degree=2).set_output(transform='pandas')
pf.fit(X_train)

PolynomialFeatures()

In [324]:
pf.get_feature_names_out()

array(['1', 'age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6',
       'age^2', 'age sex', 'age bmi', 'age bp', 'age s1', 'age s2',
       'age s3', 'age s4', 'age s5', 'age s6', 'sex^2', 'sex bmi',
       'sex bp', 'sex s1', 'sex s2', 'sex s3', 'sex s4', 'sex s5',
       'sex s6', 'bmi^2', 'bmi bp', 'bmi s1', 'bmi s2', 'bmi s3',
       'bmi s4', 'bmi s5', 'bmi s6', 'bp^2', 'bp s1', 'bp s2', 'bp s3',
       'bp s4', 'bp s5', 'bp s6', 's1^2', 's1 s2', 's1 s3', 's1 s4',
       's1 s5', 's1 s6', 's2^2', 's2 s3', 's2 s4', 's2 s5', 's2 s6',
       's3^2', 's3 s4', 's3 s5', 's3 s6', 's4^2', 's4 s5', 's4 s6',
       's5^2', 's5 s6', 's6^2'], dtype=object)

In [326]:
pipe=Pipeline(steps=[('poly',PolynomialFeatures(degree=2)),('model',LinearRegression())])

In [327]:
pipe

Pipeline(steps=[('poly', PolynomialFeatures()), ('model', LinearRegression())])

In [329]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('poly', PolynomialFeatures()), ('model', LinearRegression())])

In [330]:
pipe.predict(X_val)

array([116.39961713, 162.03316849, 175.48632579, 412.42104052,
        98.85673727,  71.31736739, 279.1807277 , 225.12372927,
        96.68550355, 105.32110584,  93.75430319, 185.92663844,
       132.65034113, 205.8854331 ,  85.18802096,  82.10072783,
       245.76287662, 289.62297057, 143.20145646, 230.79579169,
       189.76463846,  72.44049331,  70.7221366 , 212.60120758,
       157.80446282, 142.9273749 , 193.22699886, 178.05628918,
        60.78349135, 100.00376794, 127.15900579, 142.99094196,
       125.00119329, 182.83986398, 152.57158021, 282.38951078,
       119.65506208, 111.58573376, 168.83874407,  66.70371919,
        78.01739949, 105.98824386, 178.33352932, 239.42800015,
       190.54164709,  71.45090784, 102.87682208, 148.89438648,
        94.16406962, 160.67810927, 108.91861576, 132.96579661,
       124.62417444,  97.75381838, 159.10259862, 157.8752762 ,
        90.46069007, 221.64489806, 116.83866058, 104.3484041 ,
       182.42998379, 204.55857102,  88.57807601,  79.67

In [331]:
pipe.score(X_val,y_val)

0.4156399336408013

In [333]:
pipe.score(X_train, y_train)

0.6061583502354679

In [339]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import VotingRegressor

r1=LinearRegression()
r2=RandomForestRegressor(n_estimators=10,random_state=42)

er=VotingRegressor([('lr',r1),('r2',r2)])
er

VotingRegressor(estimators=[('lr', LinearRegression()),
                            ('r2',
                             RandomForestRegressor(n_estimators=10,
                                                   random_state=42))])

In [340]:
X_train @ lr.coef_.T +lr.intercept_

17     182.841348
66     148.983516
137    235.471232
245    101.835240
31      69.475758
          ...    
106     73.031677
270    192.070962
348    132.175605
435    119.483766
102    150.647483
Length: 353, dtype: float64

# Hyper Parameter Tuning Part

In [345]:
from sklearn.datasets import fetch_california_housing
housing=fetch_california_housing(as_frame=True)
c=housing.frame
c

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
0        -122.23        4.526  
1        -122.22        3.585  
2        -122.24        3.521  
3        -122.25        3.413  
4        -122.25        3.422  
...          ...          ...  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894  

[20640 rows x 9 columns]

In [348]:
from sklearn.model_selection import GridSearchCV
lr=LinearRegression()

In [349]:
param_grids={
    'fit_intercept':[True, False]
}

In [368]:
gscv_lr=GridSearchCV(lr,param_grid=param_grids,cv=3)

In [369]:
gscv_lr

GridSearchCV(cv=3, estimator=LinearRegression(),
             param_grid={'fit_intercept': [True, False]})

In [370]:
gscv_lr.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=LinearRegression(),
             param_grid={'fit_intercept': [True, False]})

In [372]:
gscv_lr.best_params_

{'fit_intercept': True}

In [373]:
best_model=gscv_lr.best_estimator_

In [375]:
best_model.score(X_train,y_train)

0.5279193863361498

---
# Bagging regressor for optimizations
---

In [377]:
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor

In [385]:
bagg_reg=BaggingRegressor(
    estimator=DecisionTreeRegressor(),
    n_estimators=50,
    bootstrap=True,
    random_state=42
)
bagg_reg.fit(X_train, y_train)

BaggingRegressor(estimator=DecisionTreeRegressor(), n_estimators=50,
                 random_state=42)

---
# Boosting regressor for optimizations
---

In [384]:
from sklearn.ensemble import GradientBoostingRegressor
gbr = GradientBoostingRegressor(
    n_estimators=150,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

gbr.fit(X_train, y_train)

print("MSE:", gbr.score(X_val, y_val))


MSE: 0.4514477330692389


---
# Har Har Mahadev
---
