<a href="https://colab.research.google.com/github/Ritesh24f1001677/MACHINE_LEARNING/blob/main/Viva_Level2_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
data=load_iris()
X=data.data
y=data.target

In [57]:
from sklearn.datasets import load_diabetes
diabetes=load_diabetes(as_frame=True)
df1=diabetes.frame
df1.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019907 -0.017646   151.0  
1 -0.039493 -0.068332 -0.092204    75.0  
2 -0.002592  0.002861 -0.025930   141.0  
3  0.034309  0.022688 -0.009362   206.0  
4 -0.002592 -0.031988 -0.046641   135.0

In [56]:
from sklearn.datasets import load_digits
digit=load_digits(as_frame=True)
df2=digit.frame
df2.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [52]:
from sklearn.datasets import load_linnerud
linnerud=load_linnerud(as_frame=True)
df3=linnerud.frame
df3.head()

Chins  Situps  Jumps  Weight  Waist  Pulse
0    5.0   162.0   60.0   191.0   36.0   50.0
1    2.0   110.0   60.0   189.0   37.0   52.0
2   12.0   101.0  101.0   193.0   38.0   58.0
3   12.0   105.0   37.0   162.0   35.0   62.0
4   13.0   155.0   58.0   189.0   35.0   46.0

In [53]:
from sklearn.datasets import load_wine
wine=load_wine(as_frame=True)
df4=wine.frame
df4.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [54]:
from sklearn.datasets import load_breast_cancer
cancer=load_breast_cancer(as_frame=True)
df5=cancer.frame
df5.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [55]:
from sklearn.datasets import fetch_california_housing
housing =fetch_california_housing(as_frame=True)
df6=housing.frame
df6.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422

In [59]:
y=df['target']
X=df.drop('target', axis=1)

In [60]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [61]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_val,y_train, y_val=train_test_split(X,y,test_size=0.2,random_state=42)

In [65]:
X_train.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                4.6               3.6                1.0               0.2
15                5.7               4.4                1.5               0.4
65                6.7               3.1                4.4               1.4
11                4.8               3.4                1.6               0.2
42                4.4               3.2                1.3               0.2

In [66]:
y_train.head()

22    0
15    0
65    1
11    0
42    0
Name: target, dtype: int64

In [69]:
X_val.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4

In [74]:
dt={
    'Category':['A','B','A','C','B'],
    'Value':[10,20,15,30,25]
    }

In [75]:
dtf=pd.DataFrame(dt)

In [80]:
dtf

Category  Value
0        A     10
1        B     20
2        A     15
3        C     30
4        B     25

In [84]:
encoded_dtf=pd.get_dummies(dtf,columns=['Category'],dtype='float')
encoded_dtf

Value  Category_A  Category_B  Category_C
0     10         1.0         0.0         0.0
1     20         0.0         1.0         0.0
2     15         1.0         0.0         0.0
3     30         0.0         0.0         1.0
4     25         0.0         1.0         0.0

In [86]:
encoded_dtf

Value  Category_A  Category_B  Category_C
0     10         1.0         0.0         0.0
1     20         0.0         1.0         0.0
2     15         1.0         0.0         0.0
3     30         0.0         0.0         1.0
4     25         0.0         1.0         0.0

# PCA principle component features

In [87]:
# principle features,  like suppose we have 4 features, so we can get 2 features,
# get best features
# it is also called dimensionality reduction
# X1, X2, X3, X4, so we cannot able to visualize all the 4 feauteres.
# X1, X2, X3-----------> X1,X4
# it can take a combination of the data and do the dimensionality redution.....


In [99]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)

In [100]:
?pca

In [101]:
from sklearn.datasets import load_iris
iris=load_iris(as_frame=True)
dtf7=iris.frame
dtf7.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [102]:
iris_df=dtf7.drop('target',axis=1)

In [103]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [104]:
iris_pca=pca.fit_transform(iris_df)

In [105]:
iris_pca

array([[-2.68412563,  0.31939725],
       [-2.71414169, -0.17700123],
       [-2.88899057, -0.14494943],
       [-2.74534286, -0.31829898],
       [-2.72871654,  0.32675451],
       [-2.28085963,  0.74133045],
       [-2.82053775, -0.08946138],
       [-2.62614497,  0.16338496],
       [-2.88638273, -0.57831175],
       [-2.6727558 , -0.11377425],
       [-2.50694709,  0.6450689 ],
       [-2.61275523,  0.01472994],
       [-2.78610927, -0.235112  ],
       [-3.22380374, -0.51139459],
       [-2.64475039,  1.17876464],
       [-2.38603903,  1.33806233],
       [-2.62352788,  0.81067951],
       [-2.64829671,  0.31184914],
       [-2.19982032,  0.87283904],
       [-2.5879864 ,  0.51356031],
       [-2.31025622,  0.39134594],
       [-2.54370523,  0.43299606],
       [-3.21593942,  0.13346807],
       [-2.30273318,  0.09870885],
       [-2.35575405, -0.03728186],
       [-2.50666891, -0.14601688],
       [-2.46882007,  0.13095149],
       [-2.56231991,  0.36771886],
       [-2.63953472,

In [106]:
pca.explained_variance_ratio_


array([0.92461872, 0.05306648])

In [107]:
pca.explained_variance_

array([4.22824171, 0.24267075])

In [111]:
pca.get_feature_names_out()

array(['pca0', 'pca1'], dtype=object)

In [112]:
?pca

In [113]:
pca.singular_values_

array([25.09996044,  6.01314738])

In [114]:
pca.noise_variance_

np.float64(0.05102229650817785)

In [121]:
pca.components_

array([[ 0.36138659, -0.08452251,  0.85667061,  0.3582892 ],
       [ 0.65658877,  0.73016143, -0.17337266, -0.07548102]])

In [123]:
pd.DataFrame(pca.components_, columns=iris_df.columns)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.361387         -0.084523           0.856671          0.358289
1           0.656589          0.730161          -0.173373         -0.075481

In [124]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer

In [125]:
pipe=Pipeline([
    ('si',SimpleImputer()),
    ('ms',MinMaxScaler())
])

In [126]:
pipe

Pipeline(steps=[('si', SimpleImputer()), ('ms', MinMaxScaler())])

In [128]:
iris_t=pipe.fit_transform(iris_pca)

In [129]:
iris_t

array([[0.07688326, 0.60048735],
       [0.07260713, 0.41246733],
       [0.04769793, 0.42460754],
       [0.06816217, 0.35894822],
       [0.07053078, 0.60327405],
       [0.13433306, 0.76030228],
       [0.05744981, 0.44562465],
       [0.08514326, 0.54139484],
       [0.04806944, 0.26046361],
       [0.07850302, 0.43641571],
       [0.10212435, 0.72384146],
       [0.08705078, 0.48508902],
       [0.06235453, 0.39045681],
       [0.        , 0.28580972],
       [0.08249271, 0.9259885 ],
       [0.11934907, 0.98632542],
       [0.08551609, 0.78656951],
       [0.08198749, 0.59762837],
       [0.14587803, 0.81011357],
       [0.09057938, 0.67403017],
       [0.13014519, 0.62773923],
       [0.09688773, 0.64351498],
       [0.00112036, 0.53006327],
       [0.13121693, 0.51689758],
       [0.12366351, 0.4653886 ],
       [0.10216398, 0.42420322],
       [0.10755597, 0.52911007],
       [0.09423586, 0.61879005],
       [0.08323574, 0.59770065],
       [0.08431065, 0.40490712],
       [0.

In [130]:
pipe['si']

SimpleImputer()

In [131]:
pipe['ms']

MinMaxScaler()

In [132]:
pipe.get_params()

{'memory': None,
 'steps': [('si', SimpleImputer()), ('ms', MinMaxScaler())],
 'transform_input': None,
 'verbose': False,
 'si': SimpleImputer(),
 'ms': MinMaxScaler(),
 'si__add_indicator': False,
 'si__copy': True,
 'si__fill_value': None,
 'si__keep_empty_features': False,
 'si__missing_values': nan,
 'si__strategy': 'mean',
 'ms__clip': False,
 'ms__copy': True,
 'ms__feature_range': (0, 1)}

In [134]:
dtf

Category  Value
0        A     10
1        B     20
2        A     15
3        C     30
4        B     25

In [135]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder

In [142]:
ct=ColumnTransformer([
    ('si',SimpleImputer(strategy='most_frequent'),['Category','Value']),
    ('le',LabelEncoder(),['Category']),
    ('ms',MinMaxScaler(),["Value"])
])

In [143]:
ct

ColumnTransformer(transformers=[('si', SimpleImputer(strategy='most_frequent'),
                                 ['Category', 'Value']),
                                ('le', LabelEncoder(), ['Category']),
                                ('ms', MinMaxScaler(), ['Value'])])